### ISSUE TITLE
[Request] onAdminPlayerConnect

### ISSUE THREAD

**Issue by mrc4tt** [lengran/CS2AnnouncementBroadcaster#1]
It would be cool if there were options for an onAdminPlayerConnect to make some announcement broadcasts for admins.

**Comment by lengran** [comment]
I'll do it for you. But would you mind share some use cases for this type of messages? I want to know how this could help server operators.

**Comment by mrc4tt** [comment]
Yep, I can share that.

This is because if I want to move the "MatchZy" plugin to be loaded as normal (without having to enable it manually from `/plugins/disabled/`)

And I wanted to add this example message from onAdminPlayerConnect:
This example message. 

It would be perfect if I could use onAdminPlayerConnect on the messages.json file e.g
```
            "{GREEN}MODE: Practice Mode",
            "{GREEN}Admin can use these commands below:",
            "!{GREEN}match - {WHITE}Load match mode",
            "!{GREEN}scrim - {WHITE}Load scrim mode {GREEN}KNIFE ROUND IS OFF!",
            "!{GREEN}kr {WHITE}off/on{WHITE} - {GREEN}Decided whether the knife round: ON or OFF"
```

**Comment by lengran** [comment]
I see. I'll update the plugin as soon as possible.

**Comment by lengran** [comment]
Hi! I just made the update. [Link](https://github.com/lengran/CS2AnnouncementBroadcaster/releases/tag/v0.4)

**Comment by mavproductions** [comment]
Truly the goat @lengran

**Comment by mrc4tt** [comment]
True, @mavproductions - lengran is **GOAT!** /Miksen

**Comment by lengran** [comment]
You guys are the heroes that shape this project! <3
